#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Initialisation de $app..."

ynh_app_setting_set --key=interface_name --value="nordvpn"
ynh_app_setting_set --key=enable_killswitch --value="1"
ynh_app_setting_set --key=nordvpn_token --value=""
ynh_app_setting_set --key=country_code --value=""
ynh_app_setting_set --key=connected_server --value=""

ynh_script_progression "Installation terminée. Allez dans les Paramètres de l'app pour coller votre Access Token NordVPN."
